name = "flang-20-bug"
version = "0.1.0"
license = "license"
author = "Jorge"
maintainer = "jg4@iastate.edu"
copyright = "Copyright 2025, Jorge"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
#uncomment this to see fail with flang
#[dependencies]
#openmp ="*"
